# fly.toml app configuration file generated for api-lively-star-7981 on 2024-12-25T14:42:00-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-lively-star-7981'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    h2_backend = true

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
