name: Build and Deploy Preview
run-name: Deploying Preview for ${{ github.head_ref }}
on:
  pull_request:
    types:
      - opened
      - synchronize # Trigger on pushes to the PR branch
    paths:
      - api/**
      - .github/workflows/ci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: |
            '**/go.sum'
            '**/go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: api

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: |
            '**/go.sum'
            '**/go.mod

            - name: golangci-lint
            uses: golangci/golangci-lint-action@v6
            with:
              version: v1.60

      - name: Test
        run: make test

        working-directory: api

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.push_image.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: |
            '**/go.sum'
            '**/go.mod'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: make image
        working-directory: api

      - name: Push docker image
        id: push_image
        run: |
          make push
          cat image.txt
        working-directory: api

  preview:
    runs-on: ubuntu-latest
    needs: [build]
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Setup Helm'
        uses: azure/setup-helm@v4.2.0

      - name: 'Generate service.yaml and save to output'
        id: 'generate_service'
        working-directory: ./infra/helm
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: |-
          ./generate.sh "happened-${{ github.head_ref}}"
          cat service.yaml

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          service_account: 'github-action-service-account@happened-441602.iam.gserviceaccount.com'

      - id: deploy
        name: Deploy Preview with Cloud Run
        working-directory: infra/helm
        run: |
          ./deploy.sh "happened-${{ github.head_ref }}"
