name: Refresh Supabase

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  query-postgres:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Query PostgreSQL
        env:
          DB_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
        run: |
          psql ${{ env.DB_URL }}  -c "SELECT 1"
